CI: add coding style checker

diff --git a/.github/workflows/Cpp.yml b/.github/workflows/Cpp.yml
--- a/.github/workflows/Cpp.yml
+++ b/.github/workflows/Cpp.yml
@@ -32,8 +32,30 @@ jobs:
       run: |
         ./build.sh
 
+  check_coding_style:
+    runs-on: ubuntu-latest
+    container: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3.4.0
+        with:
+          fetch-depth: 0
+      - run: check.sh $(pwd) $(pwd)
+      - run: cat coding-style-reports.log
+      - run: |
+          if [ -s coding-style-reports.log ]
+          then
+            echo "::group::Annotation"
+            input=coding-style-reports.log
+            while IFS= read -r line
+            do
+              echo "::error:: $line"
+            done < "$input"
+            exit 1
+          fi
+
   push_to_mirror:
-    needs: [build]
+    needs: [build, check_coding_style]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3.4.0
